### ISSUE TITLE
Filter by date

### ISSUE THREAD

**Issue by davnavarro** [blackfisk-tech/vstx-data-table#2]
Hi,

I think you have a good 'product', a good job.

Is it possible to filter between dates?

Thanks,
David

**Comment by garionberg** [comment]
Filtering between values is currently not supported within the data table itself. I have typically made this use case work by creating a date filter component that is placed in the `slot-pre-controls` or `slot-post-controls`  area of the template that modifies the parent data being used for the payload prop of the data table.

**Comment by davnavarro** [comment]
Thanks Daniel,
I will study alternatives to do it as you indicate.
My problem is that I have many rows and we need to filter for hours:(
