### ISSUE TITLE
Property or method "getPagedData" is not defined

### ISSUE THREAD

**Issue by ronakjain2012** [blackfisk-tech/vstx-data-table#3]
I'm using this component in Laravel with Vue and have check all examples but didn't find any solution of this. 
Here is my code
`<template>
  <div class="container">
    <data-table :payload='data'
                :columns='columns',
                :configuration='configuration'
                :isLoading="isLoading"
    >
    </data-table>
  </div>
</template>
<script>
    import DataTable from 'vstx-data-table'

    export default {
        name: 'SampleReport',
        components: {
            'data-table': DataTable
        },
        data () {
            return {
                isLoading:false,
                data: [
                    {id: 1, title: 'row1', amount: 1},
                    {id: 2, title: 'row2', amount: 2},
                    {id: 3, title: 'row3', amount: 3},
                    {id: 4, title: 'row4', amount: 4}
                    ],
                columns: [
                    {
                        name: 'Company Name',
                        field: 'title',
                        isVisible: true,
                        sort: {
                            isSortable: true,
                            direction: 'asc',
                            order: 1
                        }
                    },
                    ],
                configuration: {
                    table: {
                        bordered: true,
                        striped: true,
                        hoverable: true,
                        fullwidth: true
                    },
                    filter: {
                        isVisible: true,
                        isAllowed: true,
                        isEvent: false
                    },
                    columns: {
                        isVisible: false,
                        isAllowed: true
                    },
                    pagination: {
                        rowsPerPage: 25
                    }
                }
            }
        },
        method :{
            getPagedData() {
                console.log('s');
            }
        }
    }
</script>
<style lang="stylus">
</style>`

**Comment by NextStepGuru** [comment]
hello! i think the problem is our documentation is out of date, i believe it has to do with Vue.use(VstxDataTable) not being called. the plugin is looking for dependencies.

try import VstxDataTable from 'vstx-data-table' and then Vue.use(VstxDataTable)

Let me know if that works for you and i'll update the documentation.

**Comment by NextStepGuru** [comment]
```
import DataTable from 'vstx-data-table'
Vue.use(DataTable)
export default {
    name: 'SampleReport',
    components: {
        'data-table': DataTable
    }...
}
```

something like that.

**Comment by markers16123** [comment]
I got a same problem.

Here is my code

```
<template>
<div>
    <data-table :payload="data"></data-table>
</div>
</template>
```

```
import DataTable from 'vstx-data-table'
export default {
    components: {
        'data-table': DataTable
    },

    data() {
        return {
            data: [
                { id: 1, title: 'row1', amount: 1 },
                { id: 2, title: 'row2', amount: 2 },
                { id: 3, title: 'row3', amount: 3 },
                { id: 4, title: 'row4', amount: 4 },
            ]
        }
    }
}
```

error in the console.

```
[Vue warn]: Property or method "getPagedData" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <DataTable> at src\vstxDataTable.vue
       <TableSimple> at src\modules\template\_components\tables\vuetiful\simple\index.vue
         <Index> at src\modules\template\_components\tables\vuetiful\index.vue
           <ContentLayout> at src\components\content-layout\index.vue
             <Index> at src\modules\template\index.vue
               <Index> at src\modules\layout\index.vue
                 <Index> at src\components\app\index.vue
                   <Root>
....
vue.esm.js?efeb:591 [Vue warn]: Error in render: "TypeError: Cannot read property 'length' of undefined"

found in

---> <DataTable> at src\vstxDataTable.vue
       <TableSimple> at src\modules\template\_components\tables\vuetiful\simple\index.vue
         <Index> at src\modules\template\_components\tables\vuetiful\index.vue
           <ContentLayout> at src\components\content-layout\index.vue
             <Index> at src\modules\template\index.vue
               <Index> at src\modules\layout\index.vue
                 <Index> at src\components\app\index.vue
                   <Root>
...
vue.esm.js?efeb:1741 TypeError: Cannot read property 'length' of undefined
    at Proxy.r (vstx-data-table.js?9605:1)
    at VueComponent.Vue._render (vue.esm.js?efeb:4544)
    at VueComponent.updateComponent (vue.esm.js?efeb:2788)
    at Watcher.get (vue.esm.js?efeb:3142)
    at new Watcher (vue.esm.js?efeb:3131)
    at mountComponent (vue.esm.js?efeb:2795)
    at VueComponent.Vue.$mount (vue.esm.js?efeb:8540)
    at VueComponent.Vue.$mount (vue.esm.js?efeb:10939)
    at init (vue.esm.js?efeb:4137)
    at createComponent (vue.esm.js?efeb:5608)
```

**Comment by markers16123** [comment]
It seems that asynchronously computed properties are not included in the object.

[screen shot](https://drive.google.com/file/d/1TQPVO0zgsN3Qz-i_U5dcLCGYcSEDO-KG/view)

and your code in mixins
```js
// vstx-data-table/src/mixins/searchFilterMixin.js
  computed: {
    getSearch () {
      return this.state.search
    },
    getSearchColumn () {
      return [this.state.searchColumn]
    },
    getFilters () {
      return this.state.filters
    }
  },
  asyncComputed: {
    getData: {
      async get () {
        // this.state.isLoading = true
        const data = ((this.state.search.length || this.getFilters.length) && this.state.data.length > 0 ? this.state.data : this.getPayload)
        const result = await this.sortData(data)
        return result
      },
      default: []
    },
    getPagedData: {
      async get () {
        const result = await this.sliceData(this.getData)
        // this.$nextTick(() => {
        //   this.state.isLoading = false
        // })
        return result
      },
      default: []
    }
  },
```

**Comment by markers16123** [comment]
It solved. 
To use this component, i had to configure the vue-async-computed library in main.js.

```js
import AsyncComputed from 'vue-async-computed'
Vue.use(AsyncComputed)
```

**Comment by ronakjain2012** [comment]
Thanks I'll try with this.

**Comment by NextStepGuru** [comment]
Yes, sorry. When we did the rewrite a few weeks ago to support WebWorkers to improve the speed for larger data-sets when sorting, it created this problem.

I'll update the documentation to explain this current bug.

My apologizes for creating this bug.

**Comment by NextStepGuru** [comment]
You might also have to add VueWorker to your main.js file as well. I will confirm and update documentation today.

```js
...
import AsyncComputed from 'vue-async-computed'
import VueWorker from 'vue-worker'

Vue.use(AsyncComputed)
Vue.use(VueWorker)

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})
...
```

**Comment by markers16123** [comment]
Thank you. I'll check what you have mentioned in more detail tomorrow.

**Comment by NextStepGuru** [comment]
I've updated the docs. I've also created a BulmaExample.vue example to works on vue.js-cli 3.0.

We are going to do a pretty good revamp this next week to fix alot of issues with css, icons, and the above vue.use requirements to get the components to work correctly.

**Comment by NextStepGuru** [comment]
Here is a snippet from our readme with working code. We are actively working on a rewrite to remove the dependencies for both of the AsyncComputed & VueWorker in addition to Bulma.io CSS.

```vue
<template lang="pug">
  .sample-data-table
    data-table(
      :payload="data"
    )
</template>
<script>
import DataTable from 'vstx-data-table'
 
/*
   Due to a limtation of how we built this component.
   Importing AsyncComputed & VueWorker into your main.js file or
   into your data-table component is required.
 
   We are actively working on a work-around to prevent this
   from being required to use this component.
   This bug was introduced when we added support for
   data-sets with 25k+ records.
*/
import AsyncComputed from 'vue-async-computed'
import VueWorker from 'vue-worker'
 
Vue.use(AsyncComputed)
Vue.use(VueWorker)
 
/*
  Due to the how we built this component, you will have to call
  all icons. This step is NOT necessary if you use font-awesome
  library in your application already.
 */
import fontawesome from '@fortawesome/fontawesome'
import faSearch from '@fortawesome/fontawesome-free-solid/faSearch'
import faTable from '@fortawesome/fontawesome-free-solid/faTable'
import faColumns from '@fortawesome/fontawesome-free-solid/faColumns'
import faSort from '@fortawesome/fontawesome-free-solid/faSort'
import faFileExcel from '@fortawesome/fontawesome-free-solid/faFileExcel'
import faTimes from '@fortawesome/fontawesome-free-solid/faTimes'
import faList from '@fortawesome/fontawesome-free-solid/faList'
import faWrench from '@fortawesome/fontawesome-free-solid/faWrench'
import faAngleLeft from '@fortawesome/fontawesome-free-solid/faAngleLeft'
import faAngleRight from '@fortawesome/fontawesome-free-solid/faAngleRight'
 
fontawesome.library.add(faSearch)
fontawesome.library.add(faTable)
fontawesome.library.add(faColumns)
fontawesome.library.add(faSort)
fontawesome.library.add(faFileExcel)
fontawesome.library.add(faTimes)
fontawesome.library.add(faList)
fontawesome.library.add(faWrench)
fontawesome.library.add(faAngleLeft)
fontawesome.library.add(faAngleRight)
 
import 'bulma'
 
export default {
  name: 'SampleReport',
  components: {
    'data-table': DataTable
  },
  data () {
    return {
      data: [
        {id: 1, title: 'row1', amount: 1},
        {id: 2, title: 'row2', amount: 2},
        {id: 3, title: 'row3', amount: 3},
        {id: 4, title: 'row4', amount: 4}
      ]
    }
  }
}
</script>
<style lang="stylus">
</style>
```
